server:
  protocol: http
  host: 127.0.0.1
  port: 7150

logger:
  level: trace # off, warn, trace, error, info, debug
  format: pretty # json, pretty, compact, full
  ## Crates to log i.e *name of your crate*, sqlx, axum, etc
  crates:
    - "betterauth"
    - "axum"
    - "sqlx"
    - "tower-http"

database:
  uri: postgresql://postgres:postgres@localhost:5432/postgres
  name: postgres
  host: localhost
  port: 5432
  password: postgres
  user: postgres
  protocol: postgresql
